language: objective-c
env:
    - TMP_DIR=./tmp
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update && sudo motion repo
    - bundle config --global disable_shared_gems true
gemfile:
  - Gemfile
script:
    - bundle install
    - bundle exec rake clean
    - bundle exec rake spec
