language: objective-c
env:
    - TMP_DIR=./tmp
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update && sudo motion repo
gemfile:
  - Gemfile
script:
    - bundle install
    - ls -al vendor
    - ls -al vendor/bundle
    - bundle exec rake clean
    - bundle exec rake spec
